# Generated by Django 3.2.13 on 2022-06-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('código_de_compra', models.CharField(max_length=100)),
                ('deixe_sua_avaliação', models.CharField(max_length=100)),
            ],
        ),
    ]
