# Generated by Django 4.0.5 on 2022-06-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_de_cadastro', models.CharField(max_length=100)),
                ('CNPJ', models.CharField(max_length=100)),
                ('endereço_completo', models.CharField(max_length=100)),
                ('ramo_de_atividade', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
            ],
        ),
    ]
