# Generated by Django 3.2.13 on 2022-06-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_funcionario', models.CharField(max_length=100)),
                ('hora_de_entrada', models.CharField(max_length=100)),
                ('hora_da_saida', models.CharField(max_length=100)),
            ],
        ),
    ]
