# Generated by Django 3.2.13 on 2022-06-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_evento', models.CharField(max_length=100)),
                ('quantidade_de_pessoas_prevista', models.CharField(max_length=100)),
                ('promoções', models.CharField(max_length=100)),
            ],
        ),
    ]
